### ISSUE TITLE
Error! Cannot close file

### ISSUE THREAD

**Issue by stoken01** [jsh58/NGmerge#3] opened 2019-01-11 21:41 UTC
Running adapter-removal mode with two fastq.gz files, code below: 

./NGmerge -1 DoxEE17_D10_S1_R1_001.fastq.gz -2 DoxEE17_D10_S1_R2_001.fastq.gz -a -o DoxEE17_D10_noA -y -n 12

How do I fix this error?

**Comment by jsh58** [comment] 2019-01-11 23:29
Thanks for the question.  It is difficult to answer without more information, such as:
* Were output files `DoxEE17_D10_noA_1.fastq` and `DoxEE17_D10_noA_2.fastq` produced?
* Were any files moved while NGmerge was running?
* What is the output when the command is run with `-v`?

**Comment by stoken01** [comment] 2019-01-14 14:55
Both noA_1 and noA_2 files are produced, but they are empty
I run the command locally and don't move any files while it is running
Output when running command with -v is:

> Processing files: DoxEE17_D10_S1_R1_001.fastq.gz,DoxEE17_D10_S1_R2_001.fastq.gz
>   Fragments (pairs of reads) analyzed: 35533103
>   Adapters removed: 0
> Error! Cannot close file

**Comment by jsh58** [comment] 2019-01-14 19:16
I cannot reproduce this error, or anything similar.  Can you post part of the fastq files?  `zcat DoxEE17_D10_S1_R1_001.fastq.gz | head -n4`

Perhaps there was a compilation issue.  Are you compiling with GCC 6.3.0, zlib 1.2.8, and OpenMP 4.0?

Here are a couple other suggestions:
* run without `-y`
* run without `-n 12`

**Comment by stoken01** [comment] 2019-01-14 22:09
zcat DoxEE17_D10_S1_R1_001.fastq.gz | head -n4:

> @NS500672:512:HL22GBGX9:1:11101:18528:1056 1:N:0:TAAGGCGA
> TCTGACAACAGAGGCTTACGACNCCTTANNNNCCNANNNN
> +
> AAAAAEEEEEEEEEEEEEEEAE#EEEEE####EE#E####

I got the same errors as my last post when running -y (except now the output files are fasta.gz) or n -12

I am using NGmerge on our institution's supercomputer, so I only can use preloaded compilers and we don't have GCC 6.3.0 or OpenMP. However, another researcher at my institution has been able to use NGmerge in the same supercomputer.

**Comment by jsh58** [comment] 2019-01-15 00:41
I wish I could help but, without access to your supercomputer, there's not much I can do.  I have never seen empty outputs with NGmerge, nor an error closing a file.  If someone used NGmerge successfully on the supercomputer, I suggest you get in touch with them and reproduce their results.

**Comment by stoken01** [comment] 2019-01-15 14:30
Thank you! I'll get in touch with them.

**Closed as completed** 2019-04-14 19:38 UTC
